on: [push, pull_request]
name: CI

jobs:
  stack:
    name: GHC ${{ matrix.ghc }} && Stack ${{ matrix.stack }} 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ["2.5.1"]
        ghc:   ["8.10.3"]
        config:
          - { os: ubuntu-latest, resolver: lts-17.2 }

    steps:
    - uses: actions/checkout@v2

    - uses: haskell/actions/setup@v1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v2.1.3
      name: Cache ~/.stack/
      with:
        path: ~/.stack/
        key: stack-${{ matrix.config.os }}-${{ matrix.config.resolver }}
        
    # - name: Install codecov
    #   run: |
    #     sudo apt-get update -y && sudo apt-get install -y libcurl4-gnutls-dev
    #     git clone --depth=1 https://github.com/8c6794b6/codecov-haskell.git
    #     cd codecov-haskell
    #     stack install
        

    - name: Install dependencies
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
        
    - name: Test
      run: |
        stack test --system-ghc --coverage

    # - name: Upload coverage
    #   run: |
    #     TIX=$(find .stack-work -name 'db-test.tix' | head -1)
    #     MIX=$(find .stack-work/dist/* -iname "*.mix" | cut -d/ -f1-6)
    #     export PATH=/home/runner/.local/bin:$PATH
    #     codecov-haskell --display-report --tix=$TIX --mix-dir=$MIX db-test
